mqtt:
  serverIP: 192.168.178.32
  port: 1883
  user: chrak
  password: ******
  timeAddress: Mqtt/DT/t/1/s/BR/T
  
cmulti2MqttBridge:
  comPort : /dev/RS485-2
  baudRate : 57600

Mqtt2cmultiBridge:
  comPort : /dev/ttyS0
  baudRate : 115200
  listenTo : Mqtt/#
