mqtt:
  serverIP: 192.168.178.62
  port: 1883
  user: chrak
  password: *************
  timeAddress: Mqtt/DT/t/1/s/BR/T
  
serviceStatus:
    - serviceName: mqtt-bridge
      serviceAddress: Mqtt/SV/m/1/d/BR/T
    - serviceName: mqtt2FileBridge
      serviceAddress: Mqtt/SV/f/1/d/BR/T
    - serviceName: mqttFritzboxBridge
      serviceAddress: Mqtt/SV/z/1/d/BR/T
    - serviceName: cmulti-bridge
      serviceAddress: Mqtt/SV/c/1/d/BR/T

cmulti2MqttBridge:
  comPort : /dev/RS485-2
  baudRate : 57600

Mqtt2cmultiBridge:
  comPort : /dev/ttyS0  # war
  baudRate : 115200
  listenTo : Mqtt/#

mqtt2FileBridge:
  dataFolder: /home/pi/mqttData
  infos:
    - topic: Cmulti/IP/C/1/h/BR/F
      name: FeuchteDraußen
    - topic: Cmulti/IP/C/1/d/BR/F
      name: DruckDraußen
    - topic: Cmulti/H1/H/1/s/BR/d
      name: Heizung_Stufe_1
    - topic: Cmulti/H1/H/1/S/BR/d
      name: Heizung_Stufe_2

fritzBoxMain:
  ip: 192.168.178.1
  password: **********************
  switches:
    - setTopic: Mqtt/Fb/W/1/S/BR/T
      getTopic: Mqtt/Fb/W/1/g/BR/T
      command: WLANConfiguration1
    - setTopic: Mqtt/Fb/W/2/S/BR/T
      getTopic: Mqtt/Fb/W/2/g/BR/T
      command: WLANConfiguration2
    - setTopic: Mqtt/Fb/W/3/S/BR/T
      getTopic: Mqtt/Fb/W/3/g/BR/T
      command: WLANConfiguration3

# Mqtt/Quelle/Function/Address/Job/Target/Datatype
# 0    1      2        3       4   5      6  
