mqtt:
  serverIP: *******************************
  port: 1883
  user: *******************************
  password: ********************************
  timeAddress: Mqtt/DT/t/1/s/BR/T
  diskFreeAddress: Mqtt/DF/f/M/d/BR/T

serviceStatus:
    - serviceName: mqtt-bridge
      serviceAddress: Mqtt/SV/m/1/d/BR/T
    - serviceName: mqtt2FileBridge
      serviceAddress: Mqtt/SV/f/1/d/BR/T
    - serviceName: mqttFritzboxBridge
      serviceAddress: Mqtt/SV/z/1/d/BR/T
    - serviceName: cmulti-bridge
      serviceAddress: Mqtt/SV/c/1/d/BR/T

sonnenBatterie:
  serverAPI: *******************************
  serverPort: 8080
  requestStatus: /api/v1/status
  infoList:
    - name:    Consumption_W
      address: Mqtt/HA/E/C/a/BR/T
      sign:    1
    - name:    Production_W
      address: Mqtt/HA/E/S/a/BR/T
      sign:    1
    - name:    Pac_total_W
      address: Mqtt/HA/E/B/a/BR/T
      sign:    -1
    - name:    GridFeedIn_W
      address: Mqtt/HA/E/G/a/BR/T
      sign:    1
    - name:    RSOC
      address: Mqtt/HA/B/L/a/BR/T
      sign:    1


cmulti2MqttBridge:
  comPort : /dev/RS485-2
  baudRate : 57600

Mqtt2cmultiBridge:
  comPort : /dev/ttyS0  # war
  baudRate : 115200
  listenTo : Mqtt/#

auswertungen:
  dataFolder: /home/pi/Auswertungen


mqtt2FileBridge:
  dataFolder: /home/pi/mqttData
  infos:
    - topic: Cmulti/H1/H/1/s/BR/d
      name: Heizung_Stufe_1
    - topic: Cmulti/H1/H/1/S/BR/d
      name: Heizung_Stufe_2
    - topic: Cmulti/C1/C/1/p/BR/F
      name: Aussendruck
    - topic: Cmulti/CQ/C/1/t/BR/F
      name: Aussentemperatur
    - topic: Cmulti/CQ/C/1/h/BR/F
      name: Aussenfeuchte
    - topic: Cmulti/CQ/C/1/l/BR/F
      name: Aussenlicht
    - topic: Cmulti/C1/C/1/t/BR/F
      name: Kellertemperatur
    - topic: Cmulti/C1/C/1/h/BR/F
      name: Kellerfeuchte
    - topic: Cmulti/H1/T/a/t/BR/F
      name: Vorlauf
    - topic: Cmulti/H1/T/d/t/BR/F
      name: Ruecklauf
    - topic: Cmulti/H1/T/b/t/BR/F
      name: Wasserbereitung
    - topic: Cmulti/H1/T/c/t/BR/F
      name: Waermeerzeuger
    - name:    Verbrauch
      topic: Mqtt/HA/E/C/a/BR/T
    - name:    Solarerzeugung
      topic: Mqtt/HA/E/S/a/BR/T
    - name:    Batterieleistung
      topic: Mqtt/HA/E/B/a/BR/T
    - name:    Netzbezug
      topic: Mqtt/HA/E/G/a/BR/T
    - name:    Batterieladestatus
      topic: Mqtt/HA/B/L/a/BR/T
    - name: Pflanzenfeuchte
      topic: Cmulti/W1/F/A/i/BR/T
    - name: Pflanzentemperatur
      topic: Cmulti/W1/T/A/i/BR/T

zipAndSaveData:
  sourcePath: /home/pi/mqttData
  destPath: /home/pi/mqttDataZipped
  zipFile: mqttData.zip
  remotePath: mqttData

cloudFtpServer:
  ftpServer: *******************************
  user: *******************************
  password: *******************************
  port: 21


getFtp:
  ip: *******************************
  port: 210
  user: *******************************
  password: *******************************
  logFile: /home/pi/homeAssBackup/getFtp.log
  directories:
    -
      remotePath: /backup
      localPath:  /home/pi/homeAssBackup
      remoteCloudPath: /homeAssBackup

fritzBoxMain:
  ip: *******************************
  user: *******************************
  password: *******************************
  switches:
    - setTopic: Mqtt/Fb/W/1/S/BR/T
      getTopic: Mqtt/Fb/W/1/g/BR/T
      command: WLANConfiguration1
    - setTopic: Mqtt/Fb/W/2/S/BR/T
      getTopic: Mqtt/Fb/W/2/g/BR/T
      command: WLANConfiguration2
    - setTopic: Mqtt/Fb/W/3/S/BR/T
      getTopic: Mqtt/Fb/W/3/g/BR/T
      command: WLANConfiguration3

# Mqtt/Quelle/Function/Address/Job/Target/Datatype
# 0    1      2        3       4   5      6
