mqtt:
  serverIP: 192.168.178.62
  port: 1883
  user: chrak
  password: ********
  timeAddress: Mqtt/DT/t/1/s/BR/T
  
cmulti2MqttBridge:
  comPort : /dev/RS485-2
  baudRate : 57600
  
Mqtt2cmultiBridge:
  comPort : /dev/ttyS0  # war   
  baudRate : 115200
  listenTo : Mqtt/#

mqtt2FileBridge:
  dataFolder: /home/pi/mqttData 
  infos:
    - topic: Cmulti/IP/C/1/h/BR/F
      name: FeuchteDraußen
    - topic: Cmulti/IP/C/1/d/BR/F
      name: DruckDraußen
    - topic: Cmulti/H1/H/1/s/BR/d
      name: Heizung_Stufe_1
    - topic: Cmulti/H1/H/1/S/BR/d
      name: Heizung_Stufe_2
